### ISSUE TITLE
Pass metadata into get_configuration and subscribe_configuration

### ISSUE THREAD

**Issue by blackwood-ra** [dapr/rust-sdk#117]
Currently, there is no `metadata` argument for the client methods `get_configuration` and `subscribe_configuration`. Passing metadata is required when subscribing to config store changes with PostgreSQL.

To reproduce, use the following configstore.yaml component with a [configured local instance of PostgreSQL](https://docs.dapr.io/reference/components-reference/supported-configuration-stores/postgresql-configuration-store/#set-up-postgresql-as-configuration-store) running:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: configstore
spec:
  type: configuration.postgresql
  version: v1
  metadata:
    - name: connectionString
      value: host=localhost user=postgres password=[pg_password] port=5432 connect_timeout=10 database=[database_name]
    - name: table
      value: "config_table"
```

Without including metadata in the `subscribe_configuration`, an "Invalid Argument" Err is returned with the following message:
> failed to subscribe [_key_] from Configuration store _configstore_: unable to subscribe to '_config_table_'. pgNotifyChannel attribute cannot be empty
